[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "shape_library"
version = "0.1.0"
authors = [{ name = "Igor", email = "amashukeliim1150@gmail.com" }]
description = "A simple geometry library for calculating areas of shapes like circles and triangles."
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
]

[project.urls]
"Homepage" = "https://github.com/IgorAmashukeli/MindBox"
"Source" = "https://github.com/IgorAmashukeli/MindBox"
